version: "3.9"

services:
  front:
    image: tp-front
    networks:
      - back-front-net
    ports:
      - 80:80
  back:
    image: tp-back
    environment:
      - MONGODB_CONNECTION_URL=mongodb://mongo:27017/pizzas
    ports:
      - 8080:8080
    networks:
      - back-front-net
      - mongo-net
  mongo:
    image: mongo
    volumes:
      - mongo-volume:/data/db
    networks:
      - mongo-net
    ports:
      - 27017:27017

volumes:
  mongo-volume:

networks:
  mongo-net:
  back-front-net:
